service: api
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  stage: dev
  region: ap-south-1
functions:
  app:
    handler: lamda.universal # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true